App_Admin/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import export_users_xls, Select, Register

urlpatterns = [
    url(r'^$', login_required(Select.as_view()), name='select'),
    url(r'^register/(?P<id>\d+)/(?P<docs>\w+)/(?P<tick>\w+)/(?P<admin>\w+)/(?P<dpts>\w+)$', login_required(Register.as_view()), name='register'),
    url(r'^export/xls/$', export_users_xls, name='export_users_xls'),
    ]

App_Ticket/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import State, NewTicket,NewData, DetailTicket, ListTicket, AllListTicket, Seguiment

urlpatterns = [
    url(r'^$', login_required(State.as_view()), name='states'),
    url(r'^new/$', login_required(NewTicket.as_view()), name='new'),
    url(r'^new/data/(?P<value>\w+)$', login_required(NewData.as_view()), name='new_data'),
    url(r'^detail/(?P<id>\d+)$', login_required(DetailTicket.as_view()), name='detail'),
    url(r'^list/$', login_required(ListTicket.as_view()), name='list'),
    url(r'^alllist/$', login_required(AllListTicket.as_view()), name='alllist'),
    url(r'^seguiment/$', login_required(Seguiment.as_view()), name='seguiment'),
    url(r'^asignad/$', login_required(Seguiment.as_view()), name='asignad'),
]

corpcolina/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('dashboard.urls', namespace='dashboard')),
    url(r'^administrator/', include('App_Admin.urls', namespace='administrator')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^documentos/', include('documents.urls', namespace='document')),
    url(r'^ticket/', include('App_Ticket.urls', namespace='ticket')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
    url('^auth/', include('authentication.urls', namespace='auth')),
    url(r'^accounts/login/', include('authentication.urls')),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.shortcuts import render
def Verify(request):
    return render(request, 'verifyforzoho.html')

urlpatterns +=[
    url(r'^zohoverify/verifyforzoho.html$', Verify, name="verifyforzoho"),
]

dashboard/urls.py
from dashboard.views import Dashboard, SetDepartament
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(Dashboard), name='dashboard'),
    url(r'^setdepartament/(?P<name>\w+)$',login_required(SetDepartament), name='SetDepartament'),
]

documents/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required


from documents.views import ListPersonalized, ListPersonalizedSet, \
    Resumen, Document_create, Detalle_doc, Create_value, Active_off, Document_list, Document_list_filter, Document_edit, Edit_value, prints

urlpatterns = [
    url(r'^$', login_required(Resumen),name='home'),
    url(r'^nuevo$',login_required(Document_create),name='document_form'),
    url(r'^new/(?P<value>\w+)$',login_required(Create_value),name='create_value'),
    url(r'^editar/(?P<value>\w+)/(?P<id_value>\d+)$',login_required(Edit_value),name='edit_value'),
    url(r'^active_off/(?P<value>\w+)/(?P<id_value>\d+)$',login_required(Active_off), name='active_off'),
    url(r'^list/$', login_required(Document_list), name="documento_list"),
    url(r'^list/personalized/$', login_required(ListPersonalized.as_view()), name="documento_personalized"),
    url(r'^list/personalized/(?P<sere>\w+)/(?P<dere>\w+)/(?P<type>\w+)/(?P<date>\w+)/(?P<null>\w+)/$', login_required(ListPersonalizedSet.as_view()), name="documento_personalized_sel"),
    url(r'^list/(?P<value>\w+)/$', login_required(Document_list_filter), name="documento_list_filter"),
    url(r'^detalle/(?P<id_docum>\d+)$', login_required(Detalle_doc), name="documento_detalle"),
    url(r'^editar/(?P<id_documento>\d+)$', login_required(Document_edit), name="documento_edit"),
    url(r'^resume$', login_required(Resumen), name="resume"),
    url(r'^impreso/(?P<id_docum>\d+)$', login_required(prints), name="documento_impreso"),
#    url(r'^export/(?P<id_docum>\d+)/(?P<format>\w+)$', login_required(ExportView.as_view()), name="documento_export"),
    ]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Corporacion de Colina">
    <meta name="author" content="Octavio Cubillos">

	<title>Corporacion Colina {% block title %} {% endblock %}</title>
    {% block head %}

    {% endblock head %}
    <link rel="stylesheet" href="{% static 'css/personal.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">

     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
        <script>
        function doalert(){

            window.open("/auth/logout");
            return false;
        }
    </script>
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">Corp.</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Corporacion de Colina</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Notificaciones y tareas
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">1</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">Notificaciones</li>
              <li>
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> Ejemplo notificacion
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">Ver todas las notificaciones</a></li>
            </ul>
          </li>

          <li class="dropdown tasks-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">1</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">Tareas</li>
              <li>
                <ul class="menu">
                  <li>
                    <a href="#">
                      <h3>
                        Ejemplo tarea
                        <small class="pull-right">20%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Completa</span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer">
                <a href="#">Ver todas las taeras</a>
              </li>
            </ul>
          </li> -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ request.session.avatar }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ user.first_name }} {{ user.last_name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ request.session.avatar }}" class="img-circle" alt="User Image">

                <p>
                   {{ request.session.fullname }}
                  <small>Correo electronico</small>
                    {{ request.session.email }}

                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <p>Departamento {{ request.session.departament }}</p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">

                  <a href="https://myaccount.google.com/" class="btn btn-default btn-flat">Mi cuenta</a>
                </div>
                <div class="pull-right">
                  <a href="https://accounts.google.com/Logout" onclick="doalert()" class="btn btn-default btn-flat">Salir</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        <!--  <li>
        ######## Setting
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li> -->
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ request.session.avatar }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ request.session.username }} </p>
          <a href="#"><i class="fa fa-circle text-success"></i> En linea</a>
        </div>
      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        {% if request.session.is_superuser %}
        <li class="header">Administracion</li>
        <li><a href="{% url 'administrator:select' %}"><i class="fa fa-dashboard"></i> <span>Select</span></a></li>
          {% endif %}
          <li class="header">Departamento activo</li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-share"></i> <span>{{ request.session.departament.active.name }}</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu" style="display: none;">
                  {% for foo in request.session.departament.list %}

                    <li><a href="{% url 'dashboard:SetDepartament' foo.id %}"><i class="fa fa-circle-o"></i> {{ foo.name }}</a></li>
                  {% endfor %}

              </ul>
            </li>
      {% if request.session.docs %}
        <li class="header">Documentos</li>
        <li><a href="{% url 'document:resume' %}"><i class="fa fa-dashboard"></i> <span>Resumen</span></a></li>
        <li><a href="{% url 'document:document_form' %}"><i class="fa fa-circle-o"></i> <span>Nuevo</span></a></li>
        <li><a href="{% url 'document:documento_list' %}"><i class="fa fa-circle-o"></i> <span>Listado documentos</span></a></li>
        <li><a href="{% url 'document:documento_personalized' %}"><i class="fa fa-circle-o"></i> <span>Listar Agrupados</span></a></li>
      {% endif %}
      {% if request.session.ticket %}
          <li class="header">Ticket de trabajo</li>
          {% if request.session.tecnico %}
            <li><a href="{% url 'ticket:states' %}"><i class="fa fa-dashboard"></i> <span>Estados</span></a></li>
            <li><a href="{% url 'ticket:alllist' %}"><i class="fa fa-circle-o"></i> <span>Listado de ticket</span></a></li>
            <li><a href="{% url 'ticket:asignad' %}"><i class="fa fa-circle-o"></i> <span>Mis ticket asignados</span></a></li>
            <li><a href="{% url 'ticket:seguiment' %}"><i class="fa fa-circle-o"></i> <span>Seguimiento</span></a></li>

          {% else %}
            <li><a href="{% url 'ticket:states' %}"><i class="fa fa-dashboard"></i> <span>Estados</span></a></li>
            <li><a href="{% url 'ticket:new' %}"><i class="fa fa-circle-o"></i> <span>Nuevo</span></a></li>
            <li><a href="{% url 'ticket:list' %}"><i class="fa fa-circle-o"></i> <span>Mis Tickets</span></a></li>
            <li><a href="{% url 'ticket:seguiment' %}"><i class="fa fa-circle-o"></i> <span>Seguimiento</span></a></li>
        {% endif %}
      {% endif %}
      </ul>
    </section>
  </aside>
  <div class="content-wrapper">
    <section class="content-header">
      {% block header %}
        {% endblock header %}
    </section>

    <!-- Main content -->
    <section class="content">
        {% block content %}
        {% endblock content %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Compilacion</b> 53
    </div>
    <strong>Copyright &copy; 2017 <a href="">Oton</a>.</strong> All rights
    reserved.
  </footer>


  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<!-- Sparkline -->
<script src="{% static 'bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>

<!-- jQuery Knob Chart -->
<script src="{% static 'bower_components/jquery-knob/dist/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>


<!-- CK Editor -->
<script src="{% static 'bower_components/ckeditor/ckeditor.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>

<script src="{% static 'js/print.js' %}"></script>
<script src="{% static 'js/printThis.js' %}"></script>
{% block jquery %}

{% endblock jquery %}
</body>
</html>