App_Admin/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import export_users_xls, Select, Register

urlpatterns = [
    url(r'^$', login_required(Select.as_view()), name='select'),
    url(r'^register/(?P<id>\d+)/(?P<docs>\w+)/(?P<tick>\w+)/(?P<admin>\w+)/(?P<dpts>\w+)$', login_required(Register.as_view()), name='register'),
    url(r'^export/xls/$', export_users_xls, name='export_users_xls'),
    ]

App_Ticket/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import State, NewTicket,NewData, DetailTicket, ListTicket, AllListTicket, Seguiment

urlpatterns = [
    url(r'^$', login_required(State.as_view()), name='states'),
    url(r'^new/$', login_required(NewTicket.as_view()), name='new'),
    url(r'^new/data/(?P<value>\w+)$', login_required(NewData.as_view()), name='new_data'),
    url(r'^detail/(?P<id>\d+)$', login_required(DetailTicket.as_view()), name='detail'),
    url(r'^list/$', login_required(ListTicket.as_view()), name='list'),
    url(r'^alllist/$', login_required(AllListTicket.as_view()), name='alllist'),
    url(r'^seguiment/$', login_required(Seguiment.as_view()), name='seguiment'),
    url(r'^asignad/$', login_required(Seguiment.as_view()), name='asignad'),
]

corpcolina/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('dashboard.urls', namespace='dashboard')),
    url(r'^administrator/', include('App_Admin.urls', namespace='administrator')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^documentos/', include('documents.urls', namespace='document')),
    url(r'^ticket/', include('App_Ticket.urls', namespace='ticket')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
    url('^auth/', include('authentication.urls', namespace='auth')),
    url(r'^accounts/login/', include('authentication.urls')),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.shortcuts import render
def Verify(request):
    return render(request, 'verifyforzoho.html')

urlpatterns +=[
    url(r'^zohoverify/verifyforzoho.html$', Verify, name="verifyforzoho"),
]

documents/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required


from documents.views import ListPersonalized, ListPersonalizedSet, \
    Resumen, Document_create, Detalle_doc, Create_value, Active_off, Document_list, Document_list_filter, Document_edit, Edit_value, prints

urlpatterns = [
    url(r'^$', login_required(Resumen),name='home'),
    url(r'^nuevo$',login_required(Document_create),name='document_form'),
    url(r'^new/(?P<value>\w+)$',login_required(Create_value),name='create_value'),
    url(r'^editar/(?P<value>\w+)/(?P<id_value>\d+)$',login_required(Edit_value),name='edit_value'),
    url(r'^active_off/(?P<value>\w+)/(?P<id_value>\d+)$',login_required(Active_off), name='active_off'),
    url(r'^list/$', login_required(Document_list), name="documento_list"),
    url(r'^list/personalized/$', login_required(ListPersonalized.as_view()), name="documento_personalized"),
    url(r'^list/personalized/(?P<sere>\w+)/(?P<dere>\w+)/(?P<type>\w+)/(?P<date>\w+)/(?P<null>\w+)/$', login_required(ListPersonalizedSet.as_view()), name="documento_personalized_sel"),
    url(r'^list/(?P<value>\w+)/$', login_required(Document_list_filter), name="documento_list_filter"),
    url(r'^detalle/(?P<id_docum>\d+)$', login_required(Detalle_doc), name="documento_detalle"),
    url(r'^editar/(?P<id_documento>\d+)$', login_required(Document_edit), name="documento_edit"),
    url(r'^resume$', login_required(Resumen), name="resume"),
    url(r'^impreso/(?P<id_docum>\d+)$', login_required(prints), name="documento_impreso"),
#    url(r'^export/(?P<id_docum>\d+)/(?P<format>\w+)$', login_required(ExportView.as_view()), name="documento_export"),
    ]

App_Ticket/models.py
from django.db import models
from django.contrib.auth.models import User


class Tecnico(models.Model):
    tecnico = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.tecnico.first_name+" "+self.tecnico.last_name)

class Estado(models.Model):
    titulo = models.CharField(max_length=50)
    def __str__(self):
        return '{}'.format(self.titulo)


class Establecimiento(models.Model):
    titulo = models.CharField(max_length=50)
    def __str__(self):
        return '{}'.format(self.titulo)

class Tema(models.Model):
    titulo = models.CharField(max_length=60)
    def __str__(self):
        return '{}'.format(self.titulo)

class Ticket(models.Model):
    usuario = models.ForeignKey(User, null=False, blank=True, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, null=False, blank=True, on_delete=models.CASCADE)
    establecimiento = models.ForeignKey(Establecimiento, null=True, blank=True, on_delete=models.CASCADE)
    nom_contacto = models.CharField(max_length=50)
    ape_contacto = models.CharField(max_length=50)
    correo_contacto = models.EmailField()
    fijo_contacto = models.IntegerField(null=True, blank=True)
    celu_contacto = models.IntegerField(null=True, blank=True)
    resum_problema = models.CharField(max_length=100)
    asignado = models.IntegerField( null=True, blank=True)
    detall_problema = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    estado =  models.ForeignKey(Estado, null=False, blank=True, on_delete=models.CASCADE, default=1)
    def __str__(self):
        return '{}'.format(self.resum_problema)

class Respuestas(models.Model):
    usuario = models.ForeignKey(User, null=False, blank=True, on_delete=models.CASCADE)
    mensaje = models.TextField(null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    ticket = models.ForeignKey(Ticket, null=True, blank=True, on_delete=models.CASCADE)

class Transfer(models.Model):
    transfer = models.TextField(null=False, blank=True)

documents/models.py
from django.db import models
from django.contrib.auth.models import User
from department.models import Departament


class Communicators(models.Model):
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    job_title = models.CharField(max_length=100)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Remittent(Communicators):
    signature = models.TextField()

    def __str__(self):

        return (self.first_name + " " + self.last_name)


class Receiver(Communicators):

    def __str__(self):

        return (self.first_name + " " + self.last_name)


class Document_type(models.Model):
    titulo = models.CharField(max_length=50)

    def __str__(self):
        return self.titulo

class Document(models.Model):
    type = models.ForeignKey(Document_type, null=False, blank=True, on_delete=models.CASCADE)
    number = models.IntegerField(null=False)
    matter = models.CharField(max_length=50, null=False)
    previous = models.CharField(max_length=50, null=False)
    receiver = models.ForeignKey(Receiver, null=False, blank=True, on_delete=models.CASCADE)
    remittent = models.ForeignKey(Remittent, null=False, blank=True, on_delete=models.CASCADE)
    body = models.TextField(default='NA', null=False, blank=True)
    footer = models.TextField(default='NA', null=False, blank=True)
    year = models.TextField()
    user = models.ForeignKey(User, null=False, blank= True, on_delete=models.CASCADE)
    departament = models.ForeignKey(Departament, null=False, blank=True, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    print = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    change = models.BooleanField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return (str(self.number) + " " + self.matter)


class Alertmessage(models.Model):
    type = models.CharField(max_length=50, null=True)
    message = models.CharField(max_length=50, null=True)
    asign = models.IntegerField(null=True)

    def __str__(self):
        return self.message

templates/ticket/create.html
{% extends 'base/base.html' %}
{% block title %} Nuevo {{ name }}{% endblock %}
{% block header %}
    <h1>
        Ticket
        <small>Nuevo {{ name }}.</small>
    </h1>
{% endblock header %}
{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Por favor, complete el siguiente formulario para crear un nuevo {{ name }}.</h3>
    </div>
    <div class="box-body">
        <form method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="col-lg-10" >
                    {{ form.as_p }}
                    <!-- <input type="text" name="titulo" maxlength="60" id="id_titulo" class="form-control" required /> -->
                </div>
                <div class="col-lg-2" >
                    <button class="btn btn-primary" type='submit'>Guardar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/ticket/form.html
{% extends 'base/base.html' %}
{% block title %} Nuevo{% endblock %}
{% block header %}
    <h1>
        Ticket
        <small>Nuevo.</small>
    </h1>
{% endblock header %}
{% block content %}
    <script>window.onload = function (){CKEDITOR.replace('id_detall_problema');};</script>
<div class="box box-primary">
    <div class="box-header with-border">
        <div class="box-title">Por favor, complete el siguiente formulario para crear un nuevo ticket.</div>
    </div>
        <div class="box-body">
            <form method="post">
                {% csrf_token %}
                <div class="row" style="padding-top: 20px">
                    <div class="col-lg-6">
                        <h3>Seleccione tema.</h3>
                        <select name="tema" class="form-control" id="id_tema">
                            {% for ll in topics %}
                                <option value="{{ ll.id }}" selected>{{ ll }}</option>
                            {% endfor %}
                        </select>
                         <p align="right"><a href="{% url 'ticket:new_data' 'topic' %}">Nuevo</a></p>
                    </div>
                    <div class="col-md-6 ">
                    <h3>Establecimiento de solicitud</h3>
                        <select name="establecimiento" class="form-control" id="id_establecimiento">
                            {% for ll in establishments %}
                                <option value="{{ ll.id }}" selected>{{ ll }}</option>
                            {% endfor %}
                        </select>
                    <p align="right"><a href="{% url 'ticket:new_data' 'establishment' %}">Nuevo</a></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <h3>Informacion de contacto.</h3>
                    </div>
                    <div class="col-lg-6">
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-lg-6">
                        <label>Nombres</label>
                        <input type="text" name="nom_contacto" value="{{ user.first_name }}" required class="form-control" id="id_nom_contacto" maxlength="50" />
                    </div>
                    <div class="col-lg-6">
                        <label>Apellidos</label>
                        <input type="text" name="ape_contacto" value="{{ user.last_name }}" required class="form-control" id="id_ape_contacto" maxlength="50" />
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-lg-6">
                        <label>Correo electronico</label>
                        <input type="text" name="correo_contacto" value="{{ request.session.email }}" class="form-control" id="id_correo_contacto" maxlength="254" />
                    </div>
                    <div class="col-lg-3">
                        <label>Telefono Fijo</label>
                        <input type="text" name="fijo_contacto" value="{% ifnotequal 0 request.session.phone %} {{ request.session.phone }} {% endifnotequal %}" placeholder="Ej. 23232343" class="form-control" id="id_fijo_contacto" />
                    </div>
                    <div class="col-lg-3">
                        <label>Telefono Celular</label>
                        <input type="text" name="celu_contacto" value="{% ifnotequal 0 request.session.cellphone %} {{ request.session.cellphone }} {% endifnotequal %}" placeholder="Ej. 934122887" class="form-control" id="id_celu_contacto" />
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-lg-12">

                        <h3>Datos del problema.</h3>
                        <label>Asunto</label>
                        <input type="text" name="resum_problema" required class="form-control" id="id_resum_problema" maxlength="100" style="max-width: 400px" />
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-lg-12">
                        <label>Detalle del problema.</label>
                        <textarea name="detall_problema" required class="form-control" rows="10" id="id_detall_problema" cols="40">
                            </textarea>
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-lg-6">
                        <label>Estado del ticket.</label>
                        <input type="text" disabled class="form-control" value="En solicitud">
                    </div>
                    <div class="col-lg-6">
                        <div align="right" style="padding-top: 20px">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                            <a href="" class="btn btn-default" onclick="history.back();return false">Cancelar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/ticket/segiment.html
{% extends 'base/base.html' %}
{% block title %} Detalle de ticket{% endblock %}
{% block header %}
    <h1>
        Ticket
        <small>Seguimiento.</small>
    </h1>
{% endblock header %}
{% block content %}
    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
          <h3 class="box-title"><i class="fa fa-tag"></i> Seguimeinto de ticket</h3>
        </div>
        <div class="box-body ">
            <div class="row ">
                <form name="form" method="post">
                {% csrf_token %}
                    <div class="col-lg-5">
                        <h4>Ingrese numero de ticket que desea hacer seguimiento.</h4>
                    </div>
                    <div class="col-lg-4">
                            <input type="text" name="codigo" id="idcodigo" maxlength="6" required class="form-control">
                    </div>
                    <div class="col-lg-3">
                        <button type="submit" class="pull-right btn btn-default" value="Buscar">Buscar</button>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-lg-12" align="center">
                    <h4>{{ error }}</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block jquery %}
    <script type="application/javascript">
    window.addEventListener("load", function() {
        form.codigo.addEventListener("keypress", soloNumeros, false);
    });

    //Solo permite introducir numeros.
    function soloNumeros(e){
        var key = window.event ? e.which : e.keyCode;
        if (key < 48 || key > 57) {
            e.preventDefault();
        }
    }
    </script>
{% endblock jquery %}

templates/ticket/states.html
{% extends 'base/base.html' %}
{% block title %} Estados de ticket{% endblock %}
{% block header %}
    <h1>
        Ticket
        <small>Estados.</small>
    </h1>
{% endblock header %}
{% block content %}


    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
          <h3 class="box-title"><i class="fa fa-tag"></i> Estados</h3>
        </div>
        <div class="box-body ">


            <div class="row">
                <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-aqua">
                    <div class="inner">
                      <h3>{{ document_create }}</h3>

                      <p>Documentos creados</p>
                    </div>
                    <div class="icon">
                      <i class="fa ion-document-text"></i>
                    </div>
                    <a href="{% url 'document:documento_list' %}" class="small-box-footer">
                      Ver todos <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-green">
                    <div class="inner">
                      <h3>{{ document_printed }}</h3>

                      <p>Documentos impresos</p>
                    </div>
                    <div class="icon">
                      <i class="ion ion-printer"></i>
                    </div>
                    <a href="{% url 'document:documento_list_filter' 'printed' %}" class="small-box-footer">
                      Ver todos <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-yellow">
                    <div class="inner">
                      <h3>{{ document_pending }}</h3>

                      <p>Documentos pendientes</p>
                    </div>
                    <div class="icon">
                      <i class="ion ion-information-circled"></i>
                    </div>
                    <a href="{% url 'document:documento_list_filter' 'pending' %}" class="small-box-footer">
                      Ver todos <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-red">
                    <div class="inner">
                      <h3>{{ document_null }}</h3>

                      <p>Documentos nulos</p>
                    </div>
                    <div class="icon">
                      <i class="ion ion-android-cancel"></i>
                    </div>
                    <a href="{% url 'document:documento_list_filter' 'null' %}" class="small-box-footer">
                      Ver todos <i class="fa fa-arrow-circle-right"></i>
                    </a>
                  </div>
                </div>
                <!-- ./col -->
            </div>
      </div>

    </div>

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-tag"></i> Ultimos documentos creados.</h3>
        </div>
        <div class="box-body template-list">
            <div class="box-header with-border">
                <div style="font-size: medium" class="list-header">
                    <div class="row hidden-xs hidden-sm">
                        <div class="col-md-1" align="center" >
                            Id
                        </div>
                        <div class="col-md-3" align="center">
                            Materia
                        </div>
                        <div class="col-md-3" align="center">
                            Fecha
                        </div>
                        <div class="col-md-1" align="center">
                            Tipo
                        </div>
                        <div class="col-md-4" align="center">
                            Destinatario
                        </div>
                    </div>
                    <div class="row hidden-lg hidden-xl  hidden-md">
                        <div class="col-xs-2" align="center">
                            Id
                        </div>
                        <div class="col-xs-4" align="center">
                            Materia
                        </div>
                        <div class="col-xs-4" align="center">
                            Fecha
                        </div>
                        <div class="col-xs-2" align="center">
                            Tipo
                        </div>
                    </div>
                </div>
            </div>

            {% for document in model %}
                {% if document.activo %}
            <div class="box-header with-border body-list">
                <div data-toggle="collapse" data-parent="#accordion" href="#collapse{{ document.id }}" aria-expanded="false" class="collapsed" >
                    <div class="row hidden-xs hidden-sm row-list">
                        <div class="col-xs-1" align="center">
                            {{ document.number }}/{{ document.year }}
                        </div>
                        <div class="col-xs-3" align="center">
                            {{ document.matter }}
                        </div>
                        <div class="col-xs-3" align="center">
                            {{ document.created_at.date }}
                        </div>
                        <div class="col-xs-1" align="center">
                            {{ document.type }}
                        </div>
                        <div class="col-xs-4" align="center">
                            {{ document.receiver }}
                        </div>
                    </div>
                    <div class="row hidden-lg hidden-xl  hidden-md row-list">
                        <div class="col-xs-2" align="center">
                            {{ document.number }}/{{ document.year }}
                        </div>
                        <div class="col-xs-4" align="center">
                            {{ document.matter }}
                        </div>
                        <div class="col-xs-4" align="center">
                            {{ document.created_at.day }}/{{ document.created_at.month }}/{{ document.created_at.year }}
                        </div>
                        <div class="col-xs-2" align="center">
                            {{ document.type }}
                        </div>
                    </div>
                </div>
            </div>
            <div id="collapse{{ document.id }}" class="panel-collapse collapse " aria-expanded="false" style="height: 0px; border-bottom: 2px solid #d2d6de">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6" align="center">
                            <b>Documento N°{{ document.number }}/{{ document.year }}</b>
                        </div>
                        <div class="col-md-6" align="right">
                        {% if document.print %}
                            <a class="btn btn-block btn-primary " data-toggle="modal" data-target="#edit{{ document.id }}" style="display: inline">Editar</a>
                            {% else %}
                            <a class="btn btn-block btn-primary " href="{% url 'document:documento_edit' document.id %}" style="display: inline">Editar</a>
                            {% endif %}
                            <span style="padding-left: 20px"></span>
                            <a class="btn btn-block btn-info " href="{% url 'document:documento_detalle' document.id %}" style="display: inline" >Ver</a>
                            <span style="padding-left: 20px"></span>
                            <a class="btn btn-block btn-success " href="{% url 'document:documento_impreso' document.id %}" style="display: inline"> {% if document.print %}Reimprimir{% else %}Imprimir{% endif %}</a>
                            <span style="padding-left: 20px"></span>
                            <!--<a class="btn btn-block btn-danger btn-sm" data-toggle="modal" data-target="#con{{ document.id }}" href="{% url 'document:active_off' 'documento' document.id %}" style="display: inline"> Anular</a> -->
                            <a type="button" class="btn btn-block btn-danger" data-toggle="modal" data-target="#conf{{ document.id }}" style="display: inline">
                              Anular
                            </a>
                        </div>
                    </div>
                </div>
            </div>
                    <!-- Modal -->
                <div class="modal modal-danger fade" id="conf{{ document.id }}" tabindex="-1" role="dialog" aria-labelledby="conf{{ document.id }}Label">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="conf{{ document.id }}Label">Anular Documento</h4>
                      </div>
                      <div class="modal-body">
                        <h3> Esta seguro que desea anular el documento N°{{ document.id }}/{{ document.created_at.year }}</h3>
                          <p>Si lo anula no se podra volder a acceder a el.</p>
                      </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-outline" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-outline" onclick="location.href='{% url 'document:active_off' 'documento' document.id %}'">Anular</button>
                      </div>
                    </div>
                  </div>
                </div>
                    {% if document.print %}
                    <div class="modal modal-warning fade in" id="edit{{ document.id }}" tabindex="-1" role="dialog" aria-labelledby="edit{{ document.id }}Label">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="edit{{ document.id }}Label">editar Documento</h4>
                      </div>
                      <div class="modal-body">
                        <h3> Esta seguro que desea editar el documento N°{{ document.id }}/{{ document.created_at.year }} ya impreso?</h3>
                          <p>Si edita este documento no podra volver atras.</p>
                      </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-outline" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-outline" onclick="location.href='{% url 'document:documento_edit' document.id %}'">Editar</button>
                      </div>
                    </div>
                  </div>
                </div>
                    {% endif %}
                {% else %}
                  <div class="box-header with-border ">
                        <div data-toggle="collapse" aria-expanded="false" class="collapsed" style="color: #909090;cursor: not-allowed">
                            <div class="row hidden-xs hidden-sm row-list">
    <div class="col-xs-1" align="center">
        {{ document.number }}/{{ document.year }}
    </div>
    <div class="col-xs-3" align="center">
        {{ document.matter }}
    </div>
    <div class="col-xs-3" align="center">
        {{ document.created_at.date }}
    </div>
    <div class="col-xs-1" align="center">
        {{ document.type }}
    </div>
    <div class="col-xs-4" align="center">
        {{ document.receiver }}
    </div>
</div>
                            <div class="row hidden-lg hidden-xl  hidden-md row-list">
                        <div class="col-xs-2" align="center">
                            {{ document.number }}/{{ document.year }}
                        </div>
                        <div class="col-xs-4" align="center">
                            {{ document.matter }}
                        </div>
                        <div class="col-xs-4" align="center">
                            {{ document.created_at.day }}/{{ document.created_at.month }}/{{ document.created_at.year }}
                        </div>
                        <div class="col-xs-2" align="center">
                            {{ document.type }}
                        </div>
                    </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>


{% endblock %}