App_Admin/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import export_users_xls, Select, Register

urlpatterns = [
    url(r'^$', login_required(Select.as_view()), name='select'),
    url(r'^register/(?P<id>\d+)/(?P<docs>\w+)/(?P<tick>\w+)/(?P<admin>\w+)/(?P<dpts>\w+)$', login_required(Register.as_view()), name='register'),
    url(r'^export/xls/$', export_users_xls, name='export_users_xls'),
    ]

corpcolina/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('dashboard.urls', namespace='dashboard')),
    url(r'^administrator/', include('App_Admin.urls', namespace='administrator')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^documentos/', include('documents.urls', namespace='document')),
    url(r'^ticket/', include('App_Ticket.urls', namespace='ticket')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
    url('^auth/', include('authentication.urls', namespace='auth')),
    url(r'^accounts/login/', include('authentication.urls')),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.shortcuts import render
def Verify(request):
    return render(request, 'verifyforzoho.html')

urlpatterns +=[
    url(r'^zohoverify/verifyforzoho.html$', Verify, name="verifyforzoho"),
]

documents/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required


from documents.views import ListPersonalized, ListPersonalizedSet, \
    Resumen, Document_create, Detalle_doc, Create_value, Active_off, Document_list, Document_list_filter, Document_edit, Edit_value, prints

urlpatterns = [
    url(r'^$', login_required(Resumen),name='home'),
    url(r'^nuevo$',login_required(Document_create),name='document_form'),
    url(r'^new/(?P<value>\w+)$',login_required(Create_value),name='create_value'),
    url(r'^editar/(?P<value>\w+)/(?P<id_value>\d+)$',login_required(Edit_value),name='edit_value'),
    url(r'^active_off/(?P<value>\w+)/(?P<id_value>\d+)$',login_required(Active_off), name='active_off'),
    url(r'^list/$', login_required(Document_list), name="documento_list"),
    url(r'^list/personalized/$', login_required(ListPersonalized.as_view()), name="documento_personalized"),
    url(r'^list/personalized/(?P<sere>\w+)/(?P<dere>\w+)/(?P<type>\w+)/(?P<date>\w+)/(?P<null>\w+)/$', login_required(ListPersonalizedSet.as_view()), name="documento_personalized_sel"),
    url(r'^list/(?P<value>\w+)/$', login_required(Document_list_filter), name="documento_list_filter"),
    url(r'^detalle/(?P<id_docum>\d+)$', login_required(Detalle_doc), name="documento_detalle"),
    url(r'^editar/(?P<id_documento>\d+)$', login_required(Document_edit), name="documento_edit"),
    url(r'^resume$', login_required(Resumen), name="resume"),
    url(r'^impreso/(?P<id_docum>\d+)$', login_required(prints), name="documento_impreso"),
#    url(r'^export/(?P<id_docum>\d+)/(?P<format>\w+)$', login_required(ExportView.as_view()), name="documento_export"),
    ]

documents/models.py
from django.db import models
from django.contrib.auth.models import User
from department.models import Departament


class Communicators(models.Model):
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    job_title = models.CharField(max_length=100)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Remittent(Communicators):
    signature = models.TextField()

    def __str__(self):

        return (self.first_name + " " + self.last_name)


class Receiver(Communicators):

    def __str__(self):

        return (self.first_name + " " + self.last_name)


class Document_type(models.Model):
    titulo = models.CharField(max_length=50)

    def __str__(self):
        return self.titulo

class Document(models.Model):
    type = models.ForeignKey(Document_type, null=False, blank=True, on_delete=models.CASCADE)
    number = models.IntegerField(null=False)
    matter = models.CharField(max_length=50, null=False)
    previous = models.CharField(max_length=50, null=False)
    receiver = models.ForeignKey(Receiver, null=False, blank=True, on_delete=models.CASCADE)
    remittent = models.ForeignKey(Remittent, null=False, blank=True, on_delete=models.CASCADE)
    body = models.TextField(default='NA', null=False, blank=True)
    footer = models.TextField(default='NA', null=False, blank=True)
    year = models.TextField()
    user = models.ForeignKey(User, null=False, blank= True, on_delete=models.CASCADE)
    departament = models.ForeignKey(Departament, null=False, blank=True, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    print = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    change = models.BooleanField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return (str(self.number) + " " + self.matter)


class Alertmessage(models.Model):
    type = models.CharField(max_length=50, null=True)
    message = models.CharField(max_length=50, null=True)
    asign = models.IntegerField(null=True)

    def __str__(self):
        return self.message

documents/forms.py
from django import forms
from documents.models import Document, Receiver, Remittent

class DocumentForm(forms.ModelForm):

	class Meta:
		model=Document
		fields=(
			'type',
			'matter',
			'remittent',
			'receiver',
			'body',
			'footer',
			'change',
			'previous'
        )
		"""
		labels={
			'type':'Type',
			'matter':'Matter',
			'remittent':'Remittent',
			'receiver':'Receiver',
			'body':'Body',
			'footer':'Footer',
			'change':'Change',
			'previous': 'Previous'
		}
		widgets={
			'type':forms.Select(attrs={'class':'form-control'}),
			'matter': forms.TextInput(attrs={'class':'form-control'}),
			'remittent': forms.Select(attrs={'class':'form-control'}),
			'receiver': forms.Select(attrs={'class':'form-control'}),
			'body': forms.Textarea(attrs={'class':'form-control'}),
			'footer': forms.Textarea(attrs={'class':'form-control'}),
			'change':forms.CheckboxInput(attrs={'class':'form-control'}),
			'previous': forms.TextInput(attrs={'class':'form-control'}),
			}
"""
class RemittentForm(forms.ModelForm):

	class Meta:
		model = Remittent
		fields = [
			'last_name',
			'first_name',
			'job_title',
			'signature'
		]
		labels = {
			'last_name':'Last_name',
			'first_name':'First_name',
			'job_title':'Job_title',
			'signature': 'Signature',

		}
		widgets = {
			'last_name': forms.TextInput(attrs={'class':'form-control'}),
			'first_name': forms.TextInput(attrs={'class':'form-control'}),
			'job_title': forms.TextInput(attrs={'class':'form-control'}),
			'firsignaturema': forms.Textarea(attrs={'class':'form-control'}),

		}


class ReceiverForm(forms.ModelForm):

	class Meta:
		model = Receiver
		fields = [
			'last_name',
			'first_name',
			'job_title',
		]
		labels = {
			'last_name': 'Last_name',
			'first_name': 'First_name',
			'job_title': 'Job_title',

		}
		widgets = {
			'last_name': forms.TextInput(attrs={'class': 'form-control'}),
			'first_name': forms.TextInput(attrs={'class': 'form-control'}),
			'job_title': forms.TextInput(attrs={'class': 'form-control'}),
		}

documents/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse_lazy
from django.utils.html import format_html, strip_tags

from documents.models import Document, Receiver, Remittent, Document_type, Alertmessage
from documents.forms import DocumentForm, RemittentForm, ReceiverForm
from django.utils.safestring import mark_safe
from authentication.models import Departament
from django.utils.dateparse import parse_date
import datetime, time
from dashboard import views
import  ast
from django.views import View
from authentication.views import userAdmin, userDocs

template_no_valid = 'admin/error.html'

def Current_date():
    x = datetime.datetime.now()
    y = time.strftime("%A")

    def sw_dia(x):
        return {
            'Monday': 'Lunes',
            'Tuesday': 'Martes',
            'Wednesday': 'Miercoles',
            'Thursday': 'Jueves',
            'Friday': 'Viernes',
            'Saturday': 'Sabado',
            'Sunday': 'Domingo',
        }[x]

    def sw_mes(x):
        return {
            1: 'Enero',
            2: 'Febrero',
            3: 'Marzo',
            4: 'Abril',
            5: 'Mayo',
            6: 'Junio',
            7: 'Julio',
            8: 'Agosto',
            9: 'Septiembre',
            10: 'Octubre',
            11: 'Noviembre',
            12: 'Diciembre',
        }[x]

    fecha = {
        'nday': sw_dia(y),
        'day': x.day,
        'month': sw_mes(x.month),
        'year': x.year
    }
    return fecha

def Document_create(request):
    if userDocs(request) != True:
        return render(request, template_no_valid)

    depto= Departament.objects.get(id=request.session['departament']['active_id'])
    doc_for_dept= Document.objects.filter(departament=request.session['departament']['active_id'])
    date = Current_date()
    date_str = date['nday']+", "+str(date['day']) + " de " + date['month'] + " del " + str(date['year'])
    data = {}
    if request.method == 'POST':

        form = DocumentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.departament = depto
            valdos = 0
            if doc_for_dept.count() > 0:
                type = doc_for_dept.filter(type=obj.type)
                last_document = type.last()
                data['change'] = last_document.change
                obj.number = int(last_document.number) + 1
                if obj.remittent != last_document.remittent:
                    valdos = valdos + 1
                if obj.receiver != last_document.receiver:
                    valdos = valdos + 1
                if obj.body != last_document.body:
                    valdos = valdos + 1
                if obj.footer != last_document.footer:
                    valdos = valdos + 1
                if obj.matter != last_document.matter:
                    valdos = valdos + 1
                if obj.change != last_document.change:
                    valdos = valdos + 1
                if obj.previous != last_document.previous:
                    valdos = valdos + 1


                if valdos < 2:
                    act= Document.objects.get(id=last_document.id)
                    act.number=last_document.number
                    act.matter=obj.matter
                    act.remittent=obj.remittent
                    act.receiver=obj.receiver
                    act.body=obj.body
                    act.footer=obj.footer
                    act.previous=obj.previous
                    act.save()
                    obj.id = last_document.id
                    if valdos > 0:
                        request.session['alert']= 'Se a modificado el documento. '+ str(obj.id)
                else:

                    obj.year = date['year']
                    form.save()

            else:
                obj.number = 1

                #obj.creacion = date_str
                obj.year = date['year']
                obj.type_id = 1
                form.save()

            return redirect('document:documento_detalle', obj.id)
        else:
            print(form.is_valid())
            print(form.errors)
            form = DocumentForm(request.POST)

    else:
        form = DocumentForm()
    data['doc_for_dept'] = doc_for_dept
    data['edit']=True #Para activar texto enriquesido
    data['remittent'] = Remittent.objects.filter(active=True).order_by('id')
    data['receiver'] = Receiver.objects.filter(active=True).order_by('id')
    data['type'] = Document_type.objects.all().order_by('id')
    data['form']= form
    data['date']= date
    data['model']= doc_for_dept.last()
    print(data['model'].change)
    return render(request, 'document/form.html', data)

def Create_value(request, value):
    if userDocs(request) != True:
        return render(request, template_no_valid)
    data = {'value': value}
    if value == 'remittent':
        data['titulo'] = 'Remitente'
        data['tema'] = 'remitente'
        if Remittent.objects.all().count() >= 1:
            data['model'] = Remittent.objects.filter(active=True).order_by('last_name')
        data['form'] = RemittentForm()
        if request.method == 'POST':
            data['form'] = RemittentForm(request.POST)
            if data['form'].is_valid():
                data['form'].save()
            return redirect('document:document_form')
    elif value == 'receiver':
        data['titulo'] = 'Receptor'
        data['tema'] = 'receptor'
        if Receiver.objects.all().count() >= 1:
            data['model'] = Receiver.objects.all().order_by('last_name')
        data['form'] = ReceiverForm()
        if request.method == 'POST':
            data['form'] = ReceiverForm(request.POST)
            if data['form'].is_valid():
                data['form'].save()
            return redirect('document:document_form' )

    return render(request, 'document/create_value.html', data)

def Edit_value(request, value, id_value):
    if userDocs(request) != True:
        return render(request, template_no_valid)
    data = {'value': value}
    if value == 'remittent':
        data['titulo'] = 'Remitente'
        data['tema'] = 'remitente'
        data['edit'] = True  # Para activar texto enriquesido
        data['model'] = Remittent.objects.filter(active=True).order_by('first_name')
        data['modelform'] = Remittent.objects.get(id = id_value)
        if request.method == 'GET':
            data['form'] = RemittentForm(data['modelform'])

        else:
            data['form'] = RemittentForm(request.POST, instance=data['modelform'])

            if data['form'] .is_valid():
                data['form'].save()
            return redirect('document:document_form' )

    elif value == 'receiver':
        data['titulo'] = 'Receptor'
        data['tema'] = 'receptor'
        data['model'] = Receiver.objects.all().order_by('first_name')
        data['modelform'] = Receiver.objects.get(id=id_value)
        if request.method == 'GET':
            data['form'] = RemittentForm(instance=data['modelform'])
        else:
            data['form'] = ReceiverForm(request.POST, instance=data['modelform'])
            if data['form'] .is_valid():
                data['form'].save()
            return redirect('document:document_form' )

    return render(request, 'document/create_value.html', data)

def Active_off(request, **kwargs):
    if userDocs(request) != True:
        return render(request, template_no_valid)
    print(kwargs)
    value = kwargs['value']
    id_value = kwargs['id_value']
    if value == 'remittent':
        value_ = Remittent.objects.get(id=id_value)
        value_.active = False
        value_.save()
        return redirect('document:create_value', value)
    elif value == 'receiver':
        value_ = Receiver.objects.get(id=id_value)
        value_.active = False
        value_.save()
        return redirect('document:create_value', value)
    elif value == 'documento':
        value_ = Document.objects.get(id=id_value)
        value_.active = False
        value_.save()
        return redirect('document:documento_list')

def Document_edit(request, id_documento):
    if userDocs(request) != True:
        return render(request, template_no_valid)

    doc_for_dept= Document.objects.filter(departament=request.session['departament']['active_id'])
    data={'model' : Document.objects.get(id=id_documento)}
    if request.method == "GET":
        form = DocumentForm(instance=data['model'])
    else:
        form = DocumentForm(request.POST, instance=data['model'])
        print(form)
        if form.is_valid():
            form.save()
        else:
            print(form.is_valid())
            print(form.errors)
            form = DocumentForm(request.POST)
        return redirect('document:documento_list')
    date = Current_date()
    if Document.objects.filter(id=data['model'].previous).count()>0:
        data['previous'] = Document.objects.get(id=data['model'].previous)
    data['doc_for_dept'] = doc_for_dept
    data['remittent'] = Remittent.objects.filter(active=True).order_by('id')
    data['receiver'] = Receiver.objects.filter(active=True).order_by('id')
    data['type'] = Document_type.objects.all().order_by('id')
    data['form']= form
    data['date']= date
    data['editdoc']=True
    data['edit']=True
    return render(request, 'document/form.html', data)

def Document_list(request):
    if userDocs(request) != True:
        return render(request, template_no_valid)
    model = Document.objects.filter(departament=request.session['departament']['active_id']).order_by('id')
    return render(request, 'document/list.html', {'model': model})

def Document_list_filter(request, **kwargs):
    if userDocs(request) != True:
        return render(request, template_no_valid)
    model = Document.objects.filter(departament=request.session['departament']['active_id']).order_by('id')
    if kwargs['value']== 'null':

templates/document/create_value.html
{% extends 'base/base.html' %}
{% block title %} Crear {{ data.titulo }} {% endblock %}
{% block header %}
    <h1>
        Documentos
        <small>Crear {{ titulo }}.</small>
    </h1>
{% endblock header %}
{% block content %}


<script>
window.onload = function ()
{
    CKEDITOR.disableAutoInline = true;
    CKEDITOR.replace('editor1',
     {
         contentsCss: "/static/bower_components/ckeditor/value.css",
         customConfig: "/static/bower_components/ckeditor/value.js"
     });

};
</script>

    <div class="box box-default color-palette-box">
        <div class="box-header with-border">
            <h3>
            <i class="fa fa-plus fa-fw"></i> Por favor, complete el siguiente formulario para crear un nuevo {{ tema }}.
        </h3>
        </div>
        <div class="box-body">
            <form method="post">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-lg-7">
                        <label>Nombre:</label>
                        <input type="text" name="first_name" maxlength="50" value="{{ modelform.first_name }}" class="form-control" id="id_first_name" required />
                        <label style="padding-top: 20px">Apellidos</label>
                        <input type="text" name="last_name" maxlength="50" value="{{ modelform.last_name }}" class="form-control" id="id_last_name" required />
                        <label style="padding-top: 20px">Cargo:</label>
                        <input type="text" name="job_title" maxlength="100" value="{{ modelform.job_title }}" class="form-control" id="id_job_title" required />

                    </div>
                    <div class="col-lg-5" align="center">
                        {% if value == 'remittent' %}
                            <label>Firma:</label>
                             <textarea class="form-control" name="signature" id="editor1" required>
                                {{ modelform.signature|safe }}
                             </textarea>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                </div>
                <div class="row" style="padding-top: 3%">
                    <div class="col-lg-9" align="right">

                    </div>
                    <div class="col-lg-3" align="right">
                        <input type="submit" style="width: 200px" class="btn btn-primary" value="Guardar y volver" >
                    </div>
                </div>

            </form>

        </div>
    </div>

    <div class="box box-default color-palette-box">
    <div class="box-header with-border">
	<h3 class="box-title"><i class="fa fa-users fa-fw"></i> Listados de {{ tema }} registrados.</h3>
    <div class="panel-body">
        <div class="box-header with-border" style="padding-top: 1px">
            <div style="font-size: medium">
                <div class="row">
                    <div class="col-md-3" align="center">
                        <b>Nombre</b>
                    </div>
                    <div class="col-md-3" align="center">
                        <b>Apellidos</b>
                    </div>
                    <div class="col-md-6" align="center">
                        <b>Cargos</b>
                    </div>
                </div>
            </div>
        </div>

        {% if model %}
        {% for models in model %}
                {% if models.active == True %}
                    <div class="box-header with-border template-list">
                        <div data-toggle="collapse" data-parent="#accordion" href="#collapse{{ models.id }}" aria-expanded="false" class="collapsed" style="cursor: pointer">
                            <div class="row">
                                <div class="col-md-3" align="center">
                                    {{ models.first_name }}
                                </div>
                                <div class="col-md-3" align="center">
                                    {{ models.last_name }}
                                </div>
                                <div class="col-md-6" align="center">
                                    {{ models.job_title }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="collapse{{ models.id }}" class="panel-collapse collapse " aria-expanded="false" style="height: 0px;">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12" align="right" style="display: inline">
                    <a class="btn btn-block btn-primary " href="{% url 'document:edit_value' value models.id %}" style="display: inline">Editar</a>
                    <span style="padding-left: 20px"></span>
                    <a class="btn btn-block btn-danger" href="{% url 'document:active_off' value models.id %}" style="display: inline"> Eliminar</a>
                </div>
            </div>
        </div>
    </div>
                {% endif  %}
            {% endfor %}
        {% else %}
        <h3>Sin datos</h3>
        {% endif %}

		</div>
	</div>
</div>
</div>


{% endblock %}

templates/document/detail.html
{% extends 'base/base.html' %}
{% block title %} Detalle de documento N°{{ detalle.num }} {% endblock %}
{% block header %}
    <h1>
        Documentos
        <small>Detalle.</small>
    </h1>

{% endblock header %}


{% block content %}


    {% if alert %}
        {% if alert != 'printed' %}
            <div class="alert alert-danger alert-dismissable ">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ alert }} <!-- <a href="#" class="alert-link">Alert Link</a>. -->
            </div>
            {% endif %}
    {% endif %}
        <div class="box box-primary">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-md-6">
                        <h3 class="box-title"><i class="fa fa-file-text fa-fw"></i> Documento N°  {{ detail.year }}/{{ detail.number }} </h3>
                    </div>
                    <div class="col-md-6" align="right">


                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'document:documento_edit' detail.id %}"><i class="fa fa-edit"></i> Editar</a>

                        </div>
                        <div class="btn-group" style="margin-left: 4%">
                            <button class="btn btm-block btn-success" onclick="location.href='{% url 'document:documento_impreso' detail.id %}'"><i class="fa fa-print"></i> {% if detail.print %}Reimprimir{% else %}Imprimir{% endif %}</button>

                        </div>
                    </div>
                </div>
            </div>

            <div class="box-body hidden-xs" align="center">
                <div id="documento"  style="padding-top: 30px; padding-left: 50px; padding-right:50px; font-family: Arial, sans-serif;">
                    <style type="text/css">
                        .doc__ {
                            font-family: Arial, sans-serif;
                            text-align: left;
                            margin-left: 9%;
                            margin-right: 9%;
                            width: 590px;
                            height: 1100px;
                            margin-top: -4px;
                            padding-top: 0%;
                            font-size: 12pt;
                            /*font-weight: bold; */
                        }
                        .cuerpo_oficio {
                            /*text-indent: 140px; */
                            text-align: justify;
                            min-height: 380px;
                            width: auto;
                            margin-top:5px;
                            line-height: 1.3;
                        }
                        .cuerpo_carta {
                            /*text-indent: 140px; */
                            text-align: justify;
                            min-height: 200px;
                            width: auto;
                            max-width: 50px;
                            margin-top:5px;
                            line-height: 1.3;
                        }
                    /*    div { border: red 1px solid; } */
                        table, td, tr {
                     /*       border: blue 1px solid;
                            font-weight: bold;*/
                        }
                         @page
                        {
                            size: auto;
                            margin: 0mm;
                        }
                        .marker {
                                background-color: yellow;
                        }
                    </style>
                    <div class="papel">
                        <div class="doc__ ">
                            <br>
                            <div >
                                <div style="float: left;vertical-align: top; margin-top: 0px">
                                    <img src="/media/img/logo.png" alt="logo" width="170px" height="auto"><br>

                                </div>
                                <div style="text-align: left; margin-left: 50%;padding-top: 100px">

                                    <b><p>ORD.: N°{{ detail.number }}/{{ detail.year }}<br>
                                    ANT.: {% if previous %}{{ previous.matter }}{% else %} - {% endif %}<br>
                                    MAT.: {{ detail.matter }}.<br></p></b>

                                </div>
                            </div>
                            <div style="padding-top: 20px; padding-bottom: 50px">Colina,
                                {{ detail.created_at|date:"l, d" }} de
                                {{ detail.created_at|date:"F" }} de
                                {{ detail.created_at|date:"Y" }}
                            .-</div>
                        {% if detail.change %}
                            <table>
                                <tr style="vertical-align: top">
                                    <td width="50" height="100 "><b>A</b></td>
                                    <td width="50" height="100 "><b>:</b></td>
                                  <td width="475"><b>{{ detail.receiver }}<br>{{ detail.receiver.job_title }}</b></td>
                                </tr>
                                <tr style="vertical-align: top">
                                  <td width="50" height="100"><b>DE</b></td>
                                  <td width="50" height="100"><b>:</b></td>
                                  <td width="475"><b>{{ detail.remittent }}<br>{{ detail.remittent.job_title }}</b></td>
                                </tr>
                            </table>
                        {% else %}
                            <table>
                                <tr style="vertical-align: top">
                                  <td width="50" height="100"><b>DE</b></td>
                                  <td width="50" height="100"><b>:</b></td>
                                  <td width="475"><b>{{ detail.remittent }}<br>{{ detail.remittent.job_title }}</b></td>
                                </tr>
                                <tr style="vertical-align: top">
                                    <td width="50" height="100 "><b>A</b></td>
                                    <td width="50" height="100 "><b>:</b></td>
                                  <td width="475"><b>{{ detail.receiver }}<br>{{ detail.receiver.job_title }}</b></td>
                                </tr>
                            </table>
                        {% endif %}
                            {% if detalle.tipo.titulo == "Memorando" %}
                                <div class="cuerpo_carta">
                                    {{ body }}
                                </div>
                            {% else %}
                                <div class="cuerpo_oficio">
                                    {{ body|linebreaksbr }}
                                </div>
                            {% endif %}
                            <div style="float: left; font-weight: normal;margin-bottom: 40px; "><br><br><br><br><br><br><br>
                               {{ detail.footer|linebreaksbr }}
                            </div>
                            <div style="margin-left: 45%; text-align: center; width: 380px; line-height: 1">
                               {{ signature }}
                            </div>
                            <br><br><br>
                        </div>
                    </div>
                </div>
                <div align="right">**Correlativo interno {{ detalle.id }}**</div>
            </div>
            <div class="box-footer" >

            </div>
        </div>
{% endblock %}

{% block jquery %}
{% if alert == 'printed' %}
    <script type="text/javascript">
            $('#documento').printThis({});
    </script>
{% endif %}
{% endblock jquery %}