App_Admin/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .views import export_users_xls, Select, Register

urlpatterns = [
    url(r'^$', login_required(Select.as_view()), name='select'),
    url(r'^register/(?P<id>\d+)/(?P<docs>\w+)/(?P<tick>\w+)/(?P<admin>\w+)/(?P<dpts>\w+)$', login_required(Register.as_view()), name='register'),
    url(r'^export/xls/$', export_users_xls, name='export_users_xls'),
    ]

authentication/urls.py
from .views import index, logout, Newuser, ErrorPage, Espera
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^logout$', login_required(logout), name='logout'),
    url(r'^newuser$', login_required(Newuser.as_view()), name='newuser'),
    url(r'^error_page$',ErrorPage.as_view(), name='error_page'),
    url(r'^espera$',Espera.as_view(), name='espera')
]

corpcolina/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('dashboard.urls', namespace='dashboard')),
    url(r'^administrator/', include('App_Admin.urls', namespace='administrator')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^documentos/', include('documents.urls', namespace='document')),
    url(r'^ticket/', include('App_Ticket.urls', namespace='ticket')),
    url('^api/v1/', include('social_django.urls', namespace='social')),
    url('^auth/', include('authentication.urls', namespace='auth')),
    url(r'^accounts/login/', include('authentication.urls')),

]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.shortcuts import render
def Verify(request):
    return render(request, 'verifyforzoho.html')

urlpatterns +=[
    url(r'^zohoverify/verifyforzoho.html$', Verify, name="verifyforzoho"),
]

dashboard/urls.py
from dashboard.views import Dashboard, SetDepartament
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(Dashboard), name='dashboard'),
    url(r'^setdepartament/(?P<name>\w+)$',login_required(SetDepartament), name='SetDepartament'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render, redirect
from authentication.models import Logeado, Departament
from App_Ticket import models
from django.core.urlresolvers import reverse_lazy

# Create your views here.
from authentication.views import NotCorporative

def Dashboard(request):
    if NotCorporative(request)== True:
        request.session['email']=request.user.email
        data = {'title': 'Cuenta no corporativa',
                'messages': 'Su cuenta de correo es '+request.session['email']+' favor iniciar secion con cuenta adecuada.',
                'action': 'Cerrar Seccion'}
        return render(request, 'auth/error.html', data)
    elif Logeado.objects.filter(user=request.user).count()>0:
        user=Logeado.objects.get(user=request.user)
        request.session['id'] = user.user.id
        if user.user.is_superuser:
            request.session['is_superuser'] = user.user.is_superuser
        request.session['fullname'] = user.user.first_name+' '+user.user.last_name
        request.session['username'] = user.user.username
        request.session['email'] = user.user.email
        request.session['phone'] = user.phone
        request.session['cellphone'] = user.cellphone
        request.session['new'] = user.new
        request.session['avatar'] = user.avatar
        try:
            if request.session['departament']['set'] != True:
                request.session['departament'] = {}
        except Exception as e:
            request.session['departament'] = {}
            request.session['departament']['set'] = True
            print(e)
        request.session['departament']['id'] = str(user.departament).split(",")
        request.session['departament']['active_id'] = user.set_departament
        request.session['departament']['active'] = { 'id' : Departament.objects.get(id=user.set_departament).id,
                                                     'name': Departament.objects.get(id=user.set_departament).name}
        request.session['departament']['list'] =[]
        ll = ""
        for lo in request.session['departament']['id']:
           ll = ll+str(lo)
        for lo in ll.split('d'):
            if lo != "":
                request.session['departament']['list']+=[{'id' : Departament.objects.get(id=int(lo)).id,
                                                         'name': Departament.objects.get(id=int(lo)).name}]
        print(request.session['departament']['list'])
        request.session['alert'] = None

        if request.session['new'] == True:
            return redirect(reverse_lazy('auth:newuser'))
        request.session['ticket'] = user.tick
        request.session['docs'] = user.docs
        if models.Tecnico.objects.filter(tecnico = user.user).count()>0:
            request.session['tecnico'] = True
        #return render(request, 'dashboard/dashboard.html')
        if user.docs:
            return redirect(reverse_lazy('document:resume'))
        elif user.tick:
            return redirect(reverse_lazy('ticket:states'))
        else:
            return redirect(reverse_lazy('auth:newuser'))
    else:
        return redirect(reverse_lazy('auth:newuser'))


def SetDepartament(request, name):
    user = Logeado.objects.get(user=request.user)
    user.set_departament=Departament.objects.get(id=name).id

    print(Logeado.objects.get(user=request.user).set_departament)
    user.save()
    print(Logeado.objects.get(user=request.user).set_departament)
    return Dashboard(request)

templates/dashboard/dashboard.html
{% extends 'base/base.html' %}
{% block title %} Dashboard {% endblock %}
{% block header %}
    <h1>
        Dashboard
        <small>Detalle.</small>
    </h1>
{% endblock header %}

templates/dashboard/new_user.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Corporacion de Colina">
    <meta name="author" content="Octavio Cubillos">

	<title>Corporacion Colina {% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/personal.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">

     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="hold-transition skin-blue">


  <header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <span class="logo-mini">Corp.</span>
      <span class="logo-lg">Corporacion de Colina</span>
    </a>
    <nav class="navbar navbar-static-top">

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ request.session.avatar }}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ user.first_name }} {{ user.last_name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ request.session.avatar }}" class="img-circle" alt="User Image">

                <p>
                   {{ request.session.fullname }}
                  <small>Correo electronico</small>
                    {{ request.session.email }}

                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                Detalle
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                  <a href="{% url 'auth:logout' %}" class="btn btn-default btn-flat">Salir</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <div class="content-wrapper" style="margin-left: 0px;">
    <!-- Content Header (Page header) -->
    <section class="content">
        <h1>Bienvenido al sistema de <b>La Corporación de Colina</b>.</h1>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer" style="margin-left: 0px;">
    <div class="pull-right hidden-xs">
      <b>Compilacion</b> {{ request.session.compilation }}
    </div>
    <strong>Copyright &copy; 2017 <a href="">Oton</a>.</strong> All rights
    reserved.
  </footer>


  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<!-- Sparkline -->
<script src="{% static 'bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>

<!-- jQuery Knob Chart -->
<script src="{% static 'bower_components/jquery-knob/dist/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>


<!-- CK Editor -->
<script src="{% static 'bower_components/ckeditor/ckeditor.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>

<script src="{% static 'js/print.js' %}"></script>
<script src="{% static 'js/printThis.js' %}"></script>
{% if edit %}
    <script>
      $(function () {
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('editor1')
        //bootstrap WYSIHTML5 - text editor
        $('.textarea').wysihtml5()
      })
    </script>
{% endif %}
</body>
</html>